
name: Build & Deploy FM91
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy FM91
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/fm91
            git pull origin main
            git stash
